# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
<<<<<<< HEAD
  s.name = 'dm-paperclip'
  s.version = '2.4.1'
  s.platform = Gem::Platform::RUBY
  s.extra_rdoc_files = ["README.rdoc", "LICENSE" ]
  s.summary = "File attachments as attributes for DataMapper, based on the original Paperclip by Jon Yurek at Thoughtbot"
  s.description = s.summary
  s.author = "Ken Robertson"
  s.email = "ken@invalidlogic.com"
  s.homepage = "http://github.com/krobertson/dm-paperclip"

  s.require_path = 'lib'
  s.files = Dir.glob("lib/**/*")
  s.requirements = ["ImageMagick", "dm-core", "dm-validations"]
=======
  s.name = "dm-paperclip"
  s.version = "2.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ken Robertson"]
  s.date = "2012-07-20"
  s.email = "ken@invalidlogic.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "dm-paperclip.gemspec",
    "lib/dm-paperclip.rb",
    "lib/dm-paperclip/attachment.rb",
    "lib/dm-paperclip/callback_compatability.rb",
    "lib/dm-paperclip/geometry.rb",
    "lib/dm-paperclip/interpolations.rb",
    "lib/dm-paperclip/iostream.rb",
    "lib/dm-paperclip/processor.rb",
    "lib/dm-paperclip/storage.rb",
    "lib/dm-paperclip/thumbnail.rb",
    "lib/dm-paperclip/upfile.rb",
    "lib/dm-paperclip/validations.rb",
    "tasks/paperclip_tasks.rake",
    "test/attachment_test.rb",
    "test/fixtures/12k.png",
    "test/fixtures/50x50.png",
    "test/fixtures/5k.png",
    "test/fixtures/bad.png",
    "test/fixtures/s3.yml",
    "test/fixtures/text.txt",
    "test/geometry_test.rb",
    "test/helper.rb",
    "test/integration_test.rb",
    "test/iostream_test.rb",
    "test/paperclip_test.rb",
    "test/storage_test.rb",
    "test/thumbnail_test.rb"
  ]
  s.homepage = "http://invalidlogic.com/dm-paperclip/"
  s.require_paths = ["lib"]
  s.requirements = ["ImageMagick"]
  s.rubygems_version = "1.8.10"
  s.summary = "File attachments as attributes for DataMapper, based on the original Paperclip by Jon Yurek at Thoughtbot"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<extlib>, [">= 0.9.15"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.1"])
    else
      s.add_dependency(%q<dm-core>, [">= 1.2.0"])
      s.add_dependency(%q<dm-validations>, [">= 1.2.0"])
      s.add_dependency(%q<extlib>, [">= 0.9.15"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.1"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 1.2.0"])
    s.add_dependency(%q<dm-validations>, [">= 1.2.0"])
    s.add_dependency(%q<extlib>, [">= 0.9.15"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.1"])
  end
>>>>>>> other/fix_for_dm_1_2_0
end

